# -*- coding: utf-8 -*-
"""Copy of Geospatial Data Analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gBfqc9n_n1aFPnoAUqlBthWeNxXPp7Ed

In this lesson, we are going to build our first Choropleth map!
"""

import pandas as pd
import folium

url = (
    "https://raw.githubusercontent.com/python-visualization/folium/master/examples/data"
)
state_geo = f"{url}/us-states.json"
state_unemployment = f"{url}/US_Unemployment_Oct2012.csv"
state_data = pd.read_csv(state_unemployment)

state_data.head(10)

m = folium.Map(location=[48, -102], zoom_start=3)

folium.Choropleth(
    
    name="choropleth",
    data=state_data,
    columns=["State", "Unemployment"],
    key_on="feature.id",
    fill_color="PuBu",
    line_opacity=0.1,
    geo_data=state_geo,
    fill_opacity=0.3,
    
    legend_name="Unemployment Rate (%)",
).add_to(m)

folium.LayerControl().add_to(m)

m

